"""baseline schema

Revision ID: 0f1b217c2182
Revises: 
Create Date: 2026-05-25 23:18:43.718454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f1b217c2182'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('horaires', sa.Text(), nullable=True),
    sa.Column('incoming_phone_number', sa.String(length=20), nullable=True),
    sa.Column('quota_reservations', sa.Integer(), nullable=True),
    sa.Column('quota_commandes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restaurants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restaurants_incoming_phone_number'), ['incoming_phone_number'], unique=True)

    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('caller_phone', sa.String(length=20), nullable=True),
    sa.Column('call_control_id', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('reservation_code', sa.String(length=10), nullable=True),
    sa.Column('commande_code', sa.String(length=10), nullable=True),
    sa.Column('sav_flagged', sa.Boolean(), nullable=False),
    sa.Column('sav_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_logs_caller_phone'), ['caller_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_commande_code'), ['commande_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_reservation_code'), ['reservation_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_restaurant_id'), ['restaurant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_sav_flagged'), ['sav_flagged'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_logs_started_at'), ['started_at'], unique=False)

    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=Text()), nullable=False),
    sa.Column('prix_total', sa.Float(), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commandes_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_commandes_id'), ['id'], unique=False)

    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('nom_plat', sa.String(length=255), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_id'), ['id'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('personnes', sa.Integer(), nullable=False),
    sa.Column('heure', sa.String(length=10), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('call_log_id', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('cost_estimate_eur', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_logs_restaurant_id'), ['restaurant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_logs_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_id'))
        batch_op.drop_index(batch_op.f('ix_usage_logs_created_at'))

    op.drop_table('usage_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_code'))

    op.drop_table('reservations')
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_id'))

    op.drop_table('menu')
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commandes_id'))
        batch_op.drop_index(batch_op.f('ix_commandes_code'))

    op.drop_table('commandes')
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_logs_started_at'))
        batch_op.drop_index(batch_op.f('ix_call_logs_sav_flagged'))
        batch_op.drop_index(batch_op.f('ix_call_logs_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_call_logs_reservation_code'))
        batch_op.drop_index(batch_op.f('ix_call_logs_id'))
        batch_op.drop_index(batch_op.f('ix_call_logs_commande_code'))
        batch_op.drop_index(batch_op.f('ix_call_logs_caller_phone'))

    op.drop_table('call_logs')
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restaurants_incoming_phone_number'))
        batch_op.drop_index(batch_op.f('ix_restaurants_id'))

    op.drop_table('restaurants')
    # ### end Alembic commands ###
